apiVersion: apps/v1
kind: Deployment
metadata:
  name: clpaas-nest  # 기존 배포 이름
  namespace: dev
spec:
  template:
    spec:
      containers:
        - name: clpaas-nest # 기존 컨테이너 이름
          image: tmd0110/clpaas-nest:latest  # 실질적으로 업데이트할 이미지 태그