apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: backend-ingress
  namespace: dev
spec:
  ingressClassName: nginx-ingress
  rules:
  - host: backend.210-104-77-246.nip.io
    http:
      paths:
      - path: /nest
        pathType: Prefix
        backend:
          service:
            name: clpaas-nest  # 이 서비스가 존재하는지 확인
            port:
              number: 3000
      - path: /python
        pathType: Prefix
        backend:
          service:
            name: clpaas-python  # 이 서비스가 존재하는지 확인
            port:
              number: 5000
      - path: /spring
        pathType: Prefix
        backend:
          service:
            name: clpaas-spring  # 확인된 서비스 이름
            port:
              number: 8080

