resources:
- ../../base
patches:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: app-nginx1  # 실제 배포 이름
      namespace: dev    # 네임스페이스
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: nginx:latest  # 변경할 이미지 주소
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: app-nginx2  # 실제 배포 이름
      namespace: dev    # 네임스페이스
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: nginx:latest  # 변경할 이미지 주소
