apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-nginx1
  namespace: dev
  labels:
    app: app-nginx1
spec:
    spec:
      containers:
      - name: app-nginx1
        image: 210.178.40.111:32349/test-nginx:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: nexus

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-nginx2
  namespace: dev
  labels:
    app: app-nginx2
spec: 
    spec:
      containers:
      - name: app-nginx2
        image: 210.178.40.111:32349/test-nginx:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: nexus
