apiVersion: apps/v1
kind: Deployment
metadata:
  name: clpaas-spring
  namespace: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      name: clpaas-spring
  template:
    metadata:
      labels:
        name: clpaas-spring
    spec:
      containers:
        - name: clpaas-spring
          image: devyubin/clpaas-spring:latest
          ports:
            - containerPort: 8080
