apiVersion: v1
kind: Service
metadata:
  name: clpaas-spring
  namespace: dev
spec:
  type: NodePort
  selector:
    name: clpaas-spring
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30001

